replicaCount: 1

image:
  repository: ghcr.io/diyanme/employee-platform
  tag: ff942d7246dbe712e700c13f7b28f6b01046a66d

ingress:
  enabled: true
  className: traefik
  host: staging.employee.local
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1
