apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diyanme/employee-platform-gitops.git
    targetRevision: main
    path: apps/database
  destination:
    server: https://kubernetes.default.svc
    namespace: employee-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
